name: wallywiz
description: A Random Wallpaper shuffler application

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_wallpaper_manager: ^0.0.4
  desktop_wallpaper:
    path: ../desktop_wallpaper/packages/desktop_wallpaper
  dio: ^5.2.1+1
  path: ^1.8.0
  flutter_hooks: ^0.18.6
  riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  collection: ^1.17.1
  palette_generator: ^0.3.3+2
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  uuid: ^3.0.7
  duration: ^3.0.13
  logger: ^1.4.0
  shared_preferences: ^2.2.0
  form_validator: ^2.1.1
  workmanager: ^0.5.1
  marquee: ^2.2.3
  image_picker: ^1.0.1
  flutter_svg: ^2.0.7
  file_picker: ^5.3.2
  json_schema2: ^5.1.2+2
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.12
  envied: ^0.3.0+3
  window_manager: ^0.3.5
  titlebar_buttons: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

dependency_overrides:
  flutter_svg: ^2.0.7

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
