name: wallywiz
description: A Random Wallpaper shuffler application

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_wallpaper_manager: ^0.0.3
  dio: ^4.0.6
  path: ^1.8.0
  flutter_hooks: ^0.18.3
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  dio_http_cache: ^0.3.0
  collection: ^1.15.0
  flutter_background_service: ^2.0.0
  palette_generator: ^0.3.3
  cached_network_image: ^3.2.0
  path_provider: ^2.0.9
  uuid: ^3.0.6
  duration: ^3.0.11
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  form_validator: ^1.0.2
  workmanager: ^0.5.0
  marquee: ^2.2.3
  image_picker: ^0.8.5+3
  image_picker_android: ^0.8.5+1
  flutter_svg: ^1.1.1+1
  file_picker: ^5.0.0
  json_schema2: ^2.0.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
